jobs:
  # JOB-name:
  #   description: Description of job
  #   repository: github-user/github-repo
  #   branch: branch to build
  #   clone_timeout: Timeout in minutes for git clone, default 10 minutes
  #   jenkinsfile: Path and name of the Jenkinsfile, default Jenkinsfile
  #   after: [Automatically run this job after any of these jobs have been run]

  OMERO-gradle-plugins-build:
    description: Build omero-gradle-plugins
    repository: SPACEUSER/omero-gradle-plugins
    branch: SPACEBRANCH

  OMERO-build-push:
    description: Run scc merge and bump versions on omero-build
    repository: openmicroscopy/omero-build
    branch: SPACEBRANCH
    jenkinsfile: Jenkinsfile.merge

  OMERO-build-build:
    description: Build omero-build
    repository: SPACEUSER/omero-build
    branch: SPACEBRANCH_merge_trigger
    after:
      - OMERO-build-push
